[general]
name = "fp8linear"
backends = ["cuda"]
version = 1
license = "MIT"

[general.hub]
repo-id = "drbh/fp8linear"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.fp8linear]
backend = "cuda"
cuda-capabilities = [
    "8.9",
    "9.0",
    "10.0",
    "11.0",
    "12.0",
]
depends = [
    "torch",
]
src = [
    "csrc/quantize.cu",
    "csrc/fp8_gemm.cu",
]
